### PR TITLE
Modify PWM interface for IMXRT

### PR DESCRIPTION
**Pull request by HarrisonChoi750405**
1. Can change the period and duty cycle at real time
2. Can apply the low/high by ioctl function

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7ba841e54f8186f0a3b8fd37972748d54e7854ff] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [7ba841e54f8186f0a3b8fd37972748d54e7854ff] - Code Rule Check Result:
os/arch/arm/src/imxrt/imxrt_pwm.c:899: ERROR: [SPC_M_KWD] space required before the open parenthesis '('
os/arch/arm/src/imxrt/imxrt_pwm.c:902: ERROR: [SPC_M_KWD] space required before the open parenthesis '('
os/arch/arm/src/imxrt/imxrt_pwm.c:976: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
os/arch/arm/src/imxrt/imxrt_pwm.c:1211: ERROR: [IDT_M_SCH] switch and case should be at the same indent

**Comment by seinfra** [comment]
Target : [b57f01b0d128f91e1bd2ee91e8919b805bec1542] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [b57f01b0d128f91e1bd2ee91e8919b805bec1542] - Code Rule Check OK.

File: os/arch/arm/src/imxrt/imxrt_pwm.c [hunk 1]
```diff
@@ -878,7 +894,31 @@ static int imxrt_pwm_start(FAR struct pwm_lowerhalf_s *dev,
 {
 	FAR struct imxrt_pwmtimer_s *priv = (FAR struct imxrt_pwmtimer_s *)dev;
 
-	imxrt_pwm_starttimer(priv->base, kPWM_Control_Module_0 | kPWM_Control_Module_1 | kPWM_Control_Module_2);
+	printf("info->duty: %d, info->frequency: %d\n", info->duty, info->frequency);
+
+	if (priv->frequency != info->frequency) {
```
Comment (Taejun-Kwon) [inline os/arch/arm/src/imxrt/imxrt_pwm.c]: One question, Duty & Frequency has dependency?? then this is acceptable but, if they works independently, it should changed to if - if instead of if - else if.
I mean if both of duty & frequency is different, then it works properly?

File: os/arch/arm/src/imxrt/imxrt_pwm.c [hunk 2]
```diff
@@ -956,7 +996,39 @@ static int imxrt_pwm_shutdown(FAR struct pwm_lowerhalf_s *dev)
 static int imxrt_pwm_ioctl(FAR struct pwm_lowerhalf_s *dev, int cmd,
 						 unsigned long arg)
 {
-	return -ENOTTY;
+	FAR struct imxrt_pwmtimer_s *priv = (FAR struct imxrt_pwmtimer_s *)dev;
+	int ret = -ENOTTY;
+
+	switch (cmd) {
+	case PWMIOC_IDLE:
```
Comment (Taejun-Kwon) [inline os/arch/arm/src/imxrt/imxrt_pwm.c]: Could you please let me know what is different if user call below ?
fd = open("/dev/pwm");
ioctl(fd, PWMIOC_SETCHARACTERISTICS)
ioctl(fd, PWMIOC_START) ?

**Comment by seinfra** [comment]
Target : [d1d69d3c965f1ac7f87142ae3e40ddb6533ab2dd] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d1d69d3c965f1ac7f87142ae3e40ddb6533ab2dd] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cd65dbe564ef9317dfffe64368817a11b54b5794] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cd65dbe564ef9317dfffe64368817a11b54b5794] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [fbbfe55ad2815a96d478ec28af918f2eb7be630d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [fbbfe55ad2815a96d478ec28af918f2eb7be630d] - Code Rule Check (C++) OK.

File: os/arch/arm/src/imxrt/imxrt_pwm.c [hunk 3]
```diff
@@ -1119,76 +1206,76 @@ static void imxrt_pwm_drv_init3phpwm(int numPWM)
...
+	/*********** PWMA_SM1 - phase B configuration, setup PWM A channel only ************/
+	imxrt_pwm_setuppwm((PWM_Type *)PWM2_BASE, kPWM_Module_1, pwmSignal, 1, kPWM_SignedCenterAligned, pwmFrequencyInHz,
+				pwmSourceClockInHz);
+
+	/*********** PWMA_SM2 - phase C configuration, setup PWM A channel only ************/
+	imxrt_pwm_setuppwm((PWM_Type *)PWM2_BASE, kPWM_Module_2, pwmSignal, 1, kPWM_SignedCenterAligned, pwmFrequencyInHz,
+				pwmSourceClockInHz);
+	break;
+
+	#if defined(CONFIG_ARCH_CHIP_FAMILY_IMXRT105x)
```
Comment (drashti304) [inline os/arch/arm/src/imxrt/imxrt_pwm.c]: Please remove tab before #if defined

File: os/arch/arm/src/imxrt/imxrt_pwm.c [hunk 4]
```diff
@@ -1119,76 +1206,76 @@ static void imxrt_pwm_drv_init3phpwm(int numPWM)
...
+
+	/*********** PWMA_SM1 - phase B configuration, setup PWM A channel only ************/
+	imxrt_pwm_setuppwm((PWM_Type *)PWM4_BASE, kPWM_Module_1, pwmSignal, 1, kPWM_SignedCenterAligned, pwmFrequencyInHz,
+				pwmSourceClockInHz);
+
+	/*********** PWMA_SM2 - phase C configuration, setup PWM A channel only ************/
+	imxrt_pwm_setuppwm((PWM_Type *)PWM4_BASE, kPWM_Module_2, pwmSignal, 1, kPWM_SignedCenterAligned, pwmFrequencyInHz,
+				pwmSourceClockInHz);
+	break;
+	#endif
```
Comment (drashti304) [inline os/arch/arm/src/imxrt/imxrt_pwm.c]: Please remove tab before #endif
